export const projets = [
    {
      categorie: 'uxui',
      titre: 'Landing page',
      numero: 1,
      type: 'Site web',
      mockup: './assets/mockups/mockup_landing_page.png',
      description: `Le projet consiste à concevoir l'UI-UX Design d'une landing page pour un site de coaching personnalisé.`,
      outils: 'Figma, HTML, CSS',
      view: './assets/mockupsTest/jerem.jpg',
      palette: {
        carac1: '#FFFFFF',
        carac2: '#1B1B1E',
        carac3: '#C9F0FF',
        carac4: 'Roboto',
        carac5: 'Visuels',
      },
      fontFamily: "'Roboto', sans-serif;"
      
    },
    {
      categorie: 'uxui',
      titre: 'Calculatrice',
      numero: 2,
      type: 'Application mobile',
      mockup: './assets/mockups/content_mockup.png',
      description: `Le projet consiste à concevoir l'UI-UX Design d'une application mobile de calculatrice personnalisable.`,
      outils: 'Figma',
      view: './assets/mockupsTest/jerem.jpg',
      palette: {
        carac1: '#000000',
        carac2: '#E6E6F0',
        carac3: 'Pink Gradient',
        carac4: 'Purple Gradient',
        carac5: 'Cyan Gradient',
        carac6: 'Heebo',
      },
      fontFamily: "'Heebo', sans-serif;"
    },
    {
      categorie: 'uxui',
      titre: 'Page de connexion',
      numero: 3,
      type: 'Application mobile',
      mockup: './assets/mockups/page_de_connexion_1.png',
    description: `Le projet consiste à concevoir l'UI-UX Design d'une application de calculatrice personnalisable.`,
      outils: 'Figma',
      view: './assets/mockupsTest/jerem.jpg',
      palette: {
        carac1: '#000000',
        carac2: '#EEEBDA',
        carac3: '#F2AF9F',
        carac4: '#EC7D69',
        carac5: '#ABD0BF',
        carac6: '#065143',
        carac7: 'Syne Inter',
        carac8: 'Visuels',
      },
      fontFamily: "'Syne', sans-serif;" },
    {
      categorie: 'uxui',
      titre: 'Page de paiement',
      numero: 1,
      type: 'Application mobile',
      mockup: './assets/mockups/maquette_page_de_paiement.png',
    description: `Le projet consiste à concevoir l'UI-UX Design d'une landing page pour un site de coaching personnalisé.`,
      outils: 'Figma, HTML, CSS',
      view: './assets/mockupsTest/jerem.jpg',
      palette: {
        carac1: '#FFFFFF',
        carac2: '#1B1B1E',
        carac3: '#C9F0FF',
        carac4: 'Roboto',
        carac5: 'Visuels',
      },
      fontFamily: "'Roboto', sans-serif;" },
    {
      categorie: 'uxui',
      titre: 'Portfolio developpeur web',
      numero: 2,
      type: 'Type de projet',
      mockup: './assets/mockups/imac.png',
    description: `Le projet consiste à concevoir l'UI-UX Design d'une landing page pour un site de coaching personnalisé.`,
      outils: 'Figma, HTML, CSS',
      view: './assets/mockupsTest/jerem.jpg',
      palette: {
        carac1: '#FFFFFF',
        carac2: '#1B1B1E',
        carac3: '#C9F0FF',
        carac4: 'Roboto',
        carac5: 'Visuels',
      },
      fontFamily: "'Dela Gothic One', cursive;",
     },
      
    {
      categorie: '3d',
      titre: 'Le cube',
      numero: 3,
      type: 'Illustration 3D',
      mockup: './assets/mockupsTest/graphiste.png',
    description: `Le projet consiste à concevoir l'UI-UX Design d'une landing page pour un site de coaching personnalisé.`,
      outils: 'Figma, HTML, CSS',
      view: './assets/mockupsTest/jerem.jpg',
      palette: {
        carac1: '#FFFFFF',
        carac2: '#1B1B1E',
        carac3: '#C9F0FF',
        carac4: 'Roboto',
        carac5: 'Visuels',
      },
      fontFamily: "'Roboto', sans-serif;" },
    {
      categorie: 'illustration',
      titre: 'Le baiser',
      numero: 3,
      type: 'Illustration',
      mockup: './assets/mockupsTest/graphiste.png',
    description: `Le projet consiste à concevoir l'UI-UX Design d'une landing page pour un site de coaching personnalisé.`,
      outils: 'Figma, HTML, CSS',
      view: './assets/mockupsTest/jerem.jpg',
      palette: {
        carac1: '#FFFFFF',
        carac2: '#1B1B1E',
        carac3: '#C9F0FF',
        carac4: 'Roboto',
        carac5: 'Visuels',
      } },
    {
      categorie: 'illustration',
      titre: 'Perso. 01',
      numero: 3,
      type: 'Illustration',
      mockup: './assets/mockups/mockup_perso_01.png',
    description: `Le projet consiste à concevoir l'UI-UX Design d'une application de calculatrice personnalisable.`,
      outils: 'Procreate',
      view: './assets/mockupsTest/jerem.jpg',
      palette: {
        
      } },
  ];
